- hosts: mirakurun
  user: pi
  become: yes
  vars:
    pip_install_packages:
      - name: docker
      - name: docker-compose
    pip_executable: pip3
    docker_service_state: started
    docker_service_enabled: true
    docker_install_compose: false
    docker_users: pi
  roles:
    - pip3
    - geerlingguy.pip
    - geerlingguy.docker
