---
- hosts: target
  user: chummy
  tasks:
  - name: Set authorized key
    authorized_key:
      user: chummy
      state: present
      key: "{{ lookup('file', '~/.ssh/id_ssh_ed25519_dhummy.pub') }}"

