---
- name: Ensure dependencies
  apt:
    name:
      - python3-pip
      - libffi-dev
    state: present

- name: Uninstall obsolete python2
  apt:
    name:
      - python2.7-minimal
      - python-dev
      - python-backports.shutil-get-terminal-size
      - python-backports.ssl-match-hostname
    state: absent

- name: Uninstall python2 *thoroughly*
  apt:
    name: python2.7-minimal
    state: absent
    purge: yes
